version: '3.3'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'letx'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3307:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - letx-db:/var/lib/mysql
    logging:
      driver: none
  api:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    volumes:
      - ./:/letx-backend
    depends_on:
      - mysqldb
volumes:
  letx-db:
