version: '3.3'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'letx'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3307:3306
    volumes:
      - ./mysql-script:/docker-entrypoint-initdb.d
      - letx-db:/var/lib/mysql
    logging:
      driver: none
  api:
    image: node:14-alpine
    working_dir: /letx-backend
    command: yarn start:dev
    ports:
      - 3001:3000
    volumes:
      - ./:/letx-backend
    depends_on:
      - mysqldb
volumes:
  letx-db:
